name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt
      - name: Check formatting
        run: >-
          cargo fmt
          --
          --check

  test:
    name: Test ${{ matrix.rust_version }} (${{ matrix.target }})
    runs-on: ${{ matrix.target }}
    strategy:
      fail-fast: true
      matrix:
        rust_version: [stable]
        target: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust_version }}
      - name: Run tests
        run: >-
          cargo test
          --verbose

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@clippy
      - name: Run clippy
        run: >-
          cargo clippy
          --tests
